### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by redflagrul** [rupeshs/fastsdcpu#10]
Could You make a Google Colab Link?

**Comment by DevilaN** [comment]
I am affraid that colab will be difficult to use with this.
It uses local display and for colab you probably need webui working on port to connect to.

**Comment by rupeshs** [comment]
It will possible now desktop gui

**Comment by redflagrul** [comment]
I have no idea what your meaning "possible now desktop gui" there is a video of someone using inpainting not using sharing or using a different tab just to load webui it loads in the google colab notebook I don't know if it is possible but here is the video https://www.youtube.com/watch?v=gZ8YY-dPyio an the google colab link is in the describion for the code it self

**Comment by rupeshs** [comment]
@redflagrul I'll add it later.

**Comment by redflagrul** [comment]
Thanks

**Comment by rupeshs** [comment]
WIP : https://github.com/rupeshs/fastsdcpu/tree/add-colab-support

**Comment by redflagrul** [comment]
I was going to write yesterday but when you say support for Google Colab am not singing a notebook ipynb file or a link to use with Google Colab are you still in the making of a link

**Comment by rupeshs** [comment]
Some progress (FastSD CPU WebUI)
![image](https://github.com/rupeshs/fastsdcpu/assets/3255994/4ae5338c-4132-46cd-9586-2257bd874061)

**Comment by redflagrul** [comment]
So Your Still Working on it right?

**Comment by rupeshs** [comment]
@redflagrul  
Due to the limitation of using CPU/OpenVINO inside colab currently using GPU
Try this: https://colab.research.google.com/drive/1SuAqskB-_gjWLYNRFENAkIXZ1aoyINqL?usp=sharing

**Comment by redflagrul** [comment]
I heard of limitation of GPU but know CPU 🤣🤣🤣 always obstacles

**Comment by rupeshs** [comment]
Added in the latest release 1.0.0 beta 7 https://github.com/rupeshs/fastsdcpu#google-colab
