### ISSUE TITLE
Realtime code doesn't load up all 128 threads in my AMD EPYC via OPENVINO

### ISSUE THREAD

**Issue by monstercameron** [rupeshs/fastsdcpu#101]
Realtime code doesn't load up all 128 threads in my AMD EPYC. Is there a way to config openvino to load up all my cores for the experimental realtime ui?

Can you expose an option to specify CPU cores

Current benchmark results @5 steps:
100%|██████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.00it/s]
Latency: 2.96 seconds

**Comment by monstercameron** [comment]
![Screenshot 2023-12-04 164536](https://github.com/rupeshs/fastsdcpu/assets/2068787/f2bf5e0b-1f55-45c9-8705-9a672200c7d3)

**Comment by rupeshs** [comment]
Please try Pytorch(Simple disable OpenVINO). OpenVINO is mainly used for Intel CPUs.
