### ISSUE TITLE
Deprecated Parse 

### ISSUE THREAD

**Issue by BrandenSysoutHelloWorld** [rupeshs/fastsdcpu#106]
app_settings.py line 55 is using outdated code rather use model_validate

Like so ... self._config = Settings.model_validate(settings_dict)

**Comment by rupeshs** [comment]
@BrandenSysoutHelloWorld  Fixed in the master branch

**Comment by rupeshs** [comment]
@BrandenSysoutHelloWorld new release 1.0.0 beta 24 https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.24
