### ISSUE TITLE
Higher resolutions?

### ISSUE THREAD

**Issue by DiffusionAllusion** [rupeshs/fastsdcpu#108]
Hey guys thanks for this really cool software it's really nice to be able to use the CPU as it lets me make much higher resolutions even though it's slower (I max out at 640x640 on my GPU, but here I can go all the way to 1024x1024). When I use the highest resolution my CPU still never goes higher than 60% and I have plenty of RAM over so I'm wondering if there is a way to generate even higher resolution images?

Also, a stable diffusion upscaler would be really nice as well!

**Comment by rupeshs** [comment]
@DiffusionAllusion now supports upscale https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.24
