### ISSUE TITLE
is batch generation or any form of upscaling possible ?

### ISSUE THREAD

**Issue by patientx** [rupeshs/fastsdcpu#11]
First of all batch generation would be very cool to be able to do.

Is there a way that you can implement any form of upscaling here ? Not too complicated just basic 2x or 4x upscaling using any models and or maybe face repair with codeformer or something ?

Also I see lots of files on cache folder which ones are safe to delete it grows too fast too big. Maybe let us delete them with a setting or automatically delete them if not used ?

**Comment by rupeshs** [comment]
@patientx  Bacth generation support was added in the release v1.0.0 beta 7, upscaling probably in future releases.
https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.7
