### ISSUE TITLE
Plans on Android

### ISSUE THREAD

**Issue by gitknu** [rupeshs/fastsdcpu#110]
Do you have any plans on running he project for Android too? Maybe you already have such a manual?

Thank you for understanding and for such a great job you do!

**Comment by mak448a** [comment]
This probably wouldn't be easy to do; however, you should probably ask the author.

**Comment by patientx** [comment]
> Do you have any plans on running he project for Android too? Maybe you already have such a manual?
> 
> Thank you for understanding and for such a great job you do!

Just wrote a guide, https://github.com/rupeshs/fastsdcpu/discussions/123

**Comment by mak448a** [comment]
> > Do you have any plans on running he project for Android too? Maybe you already have such a manual?
> > Thank you for understanding and for such a great job you do!
> 
> Just wrote a guide, #123

Wow, I didn't think that it would be usable since it's very resource intensive! Great job!

**Comment by rupeshs** [comment]
@mak448a checkout this https://www.linkedin.com/posts/rupesh-sreeraman-2790ba31_fastsdcpu-stablediffusion-android-activity-7156280148806275072-IXaG?utm_source=share&utm_medium=member_android
