### ISSUE TITLE
[Web ui] Switching models to openvino, if guidance is left at non 1, program breaks, memory leaks. 

### ISSUE THREAD

**Issue by gobbo99** [rupeshs/fastsdcpu#111]
While using webui and switching from lora models to openvino models and not manually setting guidance to 1, program execution is blocked at inference process and machine swap memory starts getting filled and pc blocks completely after short time or process is killed eventually by some linux service. [Linux/ I7 12700f].

**Comment by rupeshs** [comment]
Recommend guidance scale is 1.0. If you want to use negative prompt increase guidance but it will take more memory .
