### ISSUE TITLE
Problems Starting the Linux start script

### ISSUE THREAD

**Issue by the-jan-peter** [rupeshs/fastsdcpu#115]
I got the Qt error, that no Qt plugins could be initialzed. 

I had to install libxcb-xinerama0

sudo apt install libxcb-xinerama0

But I suggest using the web interface 

python src/app.py -w

**Comment by rupeshs** [comment]
@the-jan-peter Which operating system?
Try a fresh install also follow the instructions in readme https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#fastsd-cpu-on-linux
