### ISSUE TITLE
window download error

### ISSUE THREAD

**Issue by Mingbru** [rupeshs/fastsdcpu#12]
i see this error when i run install.bat

C:\Users\KU MINH\Desktop\fastsdcpu-1.0.0-beta.3>cd "C:\Users\KU MINH\Desktop\fastsdcpu-1.0.0-beta.3\env\condabin\"

C:\Users\KU MINH\Desktop\fastsdcpu-1.0.0-beta.3\env\condabin>call activate.bat

C:\Users\KU MINH\Desktop\fastsdcpu-1.0.0-beta.3\env\condabin>micromamba activate
Failed to create temp directory "C:\Users\KU MINH\AppData\Local\Temp\conda-<RANDOM>\"

C:\Users\KU MINH\Desktop\fastsdcpu-1.0.0-beta.3\env\condabin>call micromamba activate "C:\Users\KU MINH\Desktop\fastsdcpu-1.0.0-beta.3\env\envs\fastsd-env"   && pip install -r "C:\Users\KU MINH\Desktop\fastsdcpu-1.0.0-beta.3\requirements.txt"
Failed to create temp directory "C:\Users\KU MINH\AppData\Local\Temp\conda-<RANDOM>\"

C:\Users\KU MINH\Desktop\fastsdcpu-1.0.0-beta.3\env\condabin>echo Env installation completed.
Env installation completed.

C:\Users\KU MINH\Desktop\fastsdcpu-1.0.0-beta.3\env\condabin>pause

how i can fix that

**Comment by rupeshs** [comment]
Try other drive not C

**Comment by Mingbru** [comment]
> Try right click install.bat and run as administrator

not working

**Comment by redflagrul** [comment]
Try Creating a New User or You Might Just to a Clean of Windows. Check Anti Virus Software Also

**Comment by JohnClaw** [comment]
> not working

If the latest update doesn't work, then try this: https://huggingface.co/datasets/4eJIoBek/PAIT-Downloads/resolve/main/fastsdcpu%5Bexperimental%5Bcant%20work%20offline%5D(openvino%20only%2C%20dont%20forget%20to%20enable%20it%20in%20settings)(dreamshaperv7-distilled-into-latent-consistency-model)-portable-win.7z

**Comment by Mingbru** [comment]
> > not working
> 
> If the latest update doesn't work, then try this: https://huggingface.co/datasets/4eJIoBek/PAIT-Downloads/resolve/main/fastsdcpu%5Bexperimental%5Bcant%20work%20offline%5D(openvino%20only%2C%20dont%20forget%20to%20enable%20it%20in%20settings)(dreamshaperv7-distilled-into-latent-consistency-model)-portable-win.7z

still not working, when I click run.bat, the window only appears for less than 1 second and then disappears

**Comment by rupeshs** [comment]
@Mingbru Try this I have removed micromamba for Windows installation in the branch https://github.com/rupeshs/fastsdcpu/tree/add-venv-install-support-windows
Please try this
You must have a Python installed
Note: pytorch does not support python 3.12 yet so make sure your python version is 3.11 or earlier.

Run these commands in a fresh folder :

git clone https://github.com/rupeshs/fastsdcpu.git
cd fastsdcpu
git checkout add-venv-install-support-windows

Double-click install.bat

**Comment by rupeshs** [comment]
Now it is also available in the master branch,micromamba removed.

**Comment by Mingbru** [comment]
> @Mingbru Try this I have removed micromamba for Windows installation in the branch https://github.com/rupeshs/fastsdcpu/tree/add-venv-install-support-windows Please try this You must have a Python installed Note: pytorch does not support python 3.12 yet so make sure your python version is 3.11 or earlier.
> 
> Run these commands in a fresh folder :
> 
> `git clone https://github.com/rupeshs/fastsdcpu.git` `cd fastsdcpu` `git checkout add-venv-install-support-windows`
> 
> Double-click `install.bat`

Thanks!
