### ISSUE TITLE
High ram usage causes segmentation fault

### ISSUE THREAD

**Issue by nicktelindert** [rupeshs/fastsdcpu#120]
The generation process eats all of my 32GB  of ram. 
This only happens when  using openvino on every models except for rupeshs/sdxl-turbo-openvino-int8.

Specs:
CPU Ryzen 5 5600G
GPU NVIDIA RTX 4070 
RAM 32GB

**Comment by rupeshs** [comment]
@nicktelindert SDXL is resource hungry, set guidance scale to 1 to reduce RAM usage , try to generate single image.
