### ISSUE TITLE
Any plans to add an API?

### ISSUE THREAD

**Issue by DiffusionAllusion** [rupeshs/fastsdcpu#122]
Thanks for the amazing software! Would be really nice if it was possible to add an API to integrate with other systems. Is it hard to add? Maybe I can help if I get some pointers on where to start

**Comment by rupeshs** [comment]
Yes it possible , probably basic API will be added later.

**Comment by rupeshs** [comment]
@DiffusionAllusion  Added API support in the  v1.0.0-beta.32 release https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.32
