### ISSUE TITLE
How to use Dreamshaper xl turbo with fastsdcpu ?

### ISSUE THREAD

**Issue by arnold408** [rupeshs/fastsdcpu#125]
Hello,
How to use Dreamshaper xl turbo with fastsdcpu ?
https://civitai.com/models/112902?modelVersionId=302806
If not, how to convert it so that it can be supported by fastsdcpu?

Not using openvino.
Using windows 11 AMD Ryzen 5 desktop. I also have linux machine.

Please suggest.
Thanks

**Comment by rupeshs** [comment]
@arnold408 Thanks for using FastSD CPU. First you need to convert ckpt model to diffusers format, please refer this https://discuss.huggingface.co/t/how-to-convert-ckpt-to-diffusers-format/35635

**Comment by arnold408** [comment]
Hi,
Thanks for your reply.
Dreamshaper xl turbo is already on huggingspace
https://huggingface.co/Lykon/dreamshaper-xl-turbo/tree/main

Can I use it in fastsdcpu or do I need to convert it as you replied above?
Thanks a lot.

**Comment by rupeshs** [comment]
@arnold408 lcm_models.txt
