### ISSUE TITLE
installation on windows

### ISSUE THREAD

**Issue by finistil** [rupeshs/fastsdcpu#126]
Could you please make a step-by-step guide on how to install FASTSDCPU on WINDOWS from scratch

**Comment by rupeshs** [comment]
@finistil Could you please check this https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#fastsd-cpu-on-windows

**Comment by finistil** [comment]
> Чи не могли б ви перевірити цю https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#fastsd-cpu-on-windows

I do not understand what exactly I need to download (I read through a translator)

**Comment by finistil** [comment]
thank you
