### ISSUE TITLE
NSFW

### ISSUE THREAD

**Issue by redflagrul** [rupeshs/fastsdcpu#13]
Still not out-puting a image I thought this was fix with the latest update. I unchecked use safety checker.

**Comment by rupeshs** [comment]
Are you using openvino?

**Comment by redflagrul** [comment]
I need more context on how would enabling openvino matter know unchecking openvino spitting out errors ![IMG_20231023_113719.jpg](https://github.com/rupeshs/fastsdcpu/assets/124815643/4e67eb1e-dd55-44e3-8bde-1e9c4822ad7c)

**Comment by patientx** [comment]
Just tested, nsfw generation works with both normal & openvino options.

**Comment by rupeshs** [comment]
Closing, unable to reproduce this issue
