### ISSUE TITLE
not able to get openvino running on pi 5

### ISSUE THREAD

**Issue by TianqiYe** [rupeshs/fastsdcpu#132]
First of all thanks for open source this project to everyone. 

I tried to reproduce the results on Raspberry pi 5, Debian 12. actually tons of headache to get it to run. no luck yet. do you have the doc or instruction to setup everything on Debian env?

just to get openvino to work on Debian is totally different process and all other dependencies have to change with it.

Thanks!

**Comment by rupeshs** [comment]
Thanks for using FastSD CPU.
Could you please check https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#fastsd-cpu-on-linux
If you find any errors please share error details too

**Comment by TianqiYe** [comment]
updated the title a bit, I tried with LCM, it works on pi 5, ~200+ sec for 4 steps 512x512 image. but I could not get openvino to work with just pip installs, but I managed to get openvino debian version to work but end up OOM (8gm ram + 5gb swap). thats how far i got.

**Comment by rupeshs** [comment]
Can you share screenshot of FastSD CPU running on RPI 5?

**Comment by TianqiYe** [comment]
the pi5 has 8gb ram, it can run any type of sd1.5 + lcm model no issue just like all the other linux system. onnx works as well. I could not find any resource online regarding running openvino + sd on pi so might be too deep into the rabbit hole. feel free to close this issue.

**Comment by rupeshs** [comment]
@TianqiYe Thanks I will add this to Readme, if you have a screenshot of fastsdcpu running on Raspberry PI 5, please share. Or You can create a pull request.
