### ISSUE TITLE
Python 3.9 required

### ISSUE THREAD

**Issue by veikk0** [rupeshs/fastsdcpu#136]
The README states the minimum Python version is 3.8, but it seems 3.9 is required because of `networkx`:

```
Starting FastSD CPU env installation...
Found python3 command
Python version : 3.8.10
...
Collecting networkx
  Using cached https://download.pytorch.org/whl/networkx-3.2.1-py3-none-any.whl (1.6 MB)
ERROR: Package 'networkx' requires a different Python: 3.8.10 not in '>=3.9'
```

I do have Python 3.9 installed but if I set it as the default version, all my distro's utilities break because they're written and tested for 3.8.

I'm on Linux Mint 20.3. I have no experience using different versions of Python, so any advice on how to do this for fastsdcpu would be appreciated.

**Comment by mirrorsonthewall** [comment]
I thought someone could just run an operating system version that has the right python version installed in a virtual machine, not sure if there is a simpler / less resource intensive way until the issue is fixed

**Comment by rupeshs** [comment]
@veikk0  Yes, networkx is a required package for torch. So as per the latest document you need to use Python 3.9 or Python 3.10 or Python 3.11
Refer: https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#fastsd-cpu-on-linux
You can try the latest release with lora support : https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.25
