### ISSUE TITLE
Web-frontend LCM-openVINO crashed hard

### ISSUE THREAD

**Issue by euneuber** [rupeshs/fastsdcpu#143]
Version 1.0.0 beta 24
Python 3.11.8
only web-frontend (qt5-gui does not work, see #140)
mode: LCM-openVINO
model: "rupeshs/sd-turbo-openvino"
inference steps: 6
image width, height: 512, 512
number of images: 6
guidance scale: 1.2
on other options
output format: PNG
Text-to-Image:
pos. prompt: "an AI robot ruling the world"
neg. prompt: (empty)

After downloading the files for openVINO the python program **crashes so hard, that even the terminal (konsole) dies!** (I never had this with any other program before!)

If this is because of the settings I chose, please guide me!

**Comment by rupeshs** [comment]
@euneuber Please refer to the memory requirements https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#memory-requirements
The guidance scale is 1.2 it will take around 15GB of system RAM for OpenVINO. Reduce the guidance scale to 1. For SDTurbo only 1 inference step is fine.
Here is the latest release with Lora models support https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.25
