### ISSUE TITLE
Installation Issues: Incompatible torch and openvino Versions in install.bat

### ISSUE THREAD

**Issue by JuanCPar** [rupeshs/fastsdcpu#155]
Installation errors for torch==2.0.1 and openvino==2023.2.0 in install.bet for FastSD CPU project, despite having the latest software versions on a Lenovo Yoga 7i laptop. 

I'm not very adept in these matters, I'm just a regular guy with a CPU plus Chat GPT trying to create as one could with Stability Matrix. I couldn't get Stability Matrix to work for my CPU and was lead here to this project.

**Comment by rupeshs** [comment]
Can you share the error description and logs, Python version?

**Comment by JuanCPar** [comment]
I'm not very familiar with coding but I'm hoping this is what you are asking for.

PS C:\Users\juanc\Desktop\FastSDCPU\fastsdcpu> .\\install.bat
Starting FastSD CPU env installation...
Python command check :OK
Python version: 3.12.2
Looking in indexes: https://download.pytorch.org/whl/cpu
ERROR: Could not find a version that satisfies the requirement torch==2.0.1 (from versions: 2.2.0+cpu, 2.2.1+cpu)
ERROR: No matching distribution found for torch==2.0.1
Collecting accelerate==0.23.0 (from -r C:\Users\juanc\Desktop\FastSDCPU\fastsdcpu\requirements.txt (line 1))
  Using cached accelerate-0.23.0-py3-none-any.whl.metadata (18 kB)
Collecting diffusers==0.23.0 (from -r C:\Users\juanc\Desktop\FastSDCPU\fastsdcpu\requirements.txt (line 2))
  Using cached diffusers-0.23.0-py3-none-any.whl.metadata (17 kB)
Collecting transformers==4.35.0 (from -r C:\Users\juanc\Desktop\FastSDCPU\fastsdcpu\requirements.txt (line 3))
  Using cached transformers-4.35.0-py3-none-any.whl.metadata (123 kB)
Collecting PyQt5 (from -r C:\Users\juanc\Desktop\FastSDCPU\fastsdcpu\requirements.txt (line 4))
  Using cached PyQt5-5.15.10-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
Collecting Pillow==9.4.0 (from -r C:\Users\juanc\Desktop\FastSDCPU\fastsdcpu\requirements.txt (line 5))
  Using cached Pillow-9.4.0.tar.gz (50.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement openvino==2023.2.0 (from versions: none)
ERROR: No matching distribution found for openvino==2023.2.0
FastSD CPU env installation completed.
