### ISSUE TITLE
Web UI slider problem

### ISSUE THREAD

**Issue by 7shi** [rupeshs/fastsdcpu#158]
When using Web UI, slider changes are frequently not reflected properly.

This is a problem on gradio and has been fixed in newer versions.

* https://github.com/gradio-app/gradio/issues/1453

After updating gradio to 4.21.0, this problem is solved.

Although in requirements.txt it is listed as `gradio==3.39.0`, I think it should be updated.

**Comment by rupeshs** [comment]
@7shi  will be fixed in the next release

**Comment by rupeshs** [comment]
Fixed in the latest release https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.30
