### ISSUE TITLE
Does Negative prompt work on lcm mode?

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#168]
Hey I can't tell if Negative prompt works for lcm mode
BTW I wanted to ask will you make text to video termux webui I've been wanting offline text to video for months but
No one has done it yet but this app is perfect for text to video. Hopefully you can make a text to video fast cpu termux webui one day:) this will make my dream come true 👍

**Comment by rupeshs** [comment]
> Hey I can't tell if Negative prompt works for lcm mode BTW I wanted to ask will you make text to video termux webui I've been wanting offline text to video for months but No one has done it yet but this app is perfect for text to video. Hopefully you can make a text to video fast cpu termux webui one day:) this will make my dream come true 👍

Yes, set guidance scale > 1.0 ( But it cause cause slow inference and high memory usage)

**Comment by rupeshs** [comment]
text to video is very process intensive , may be later :)
