### ISSUE TITLE
Cannot find python after installing python 3

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#171]
I need help I installed python but when I open start.bat it still says can't find python I even put the path to the exe in the start bat file and it still say it do I need to put it on my c drive? Where python is installed?

**Comment by Dog66609** [comment]
I think this is the same problem I had with Windows 10. What worked for me was to install Python through the Microsoft Store. In Windows 10, you can do this easily. Simply typing python in cmd brought me right to the page, or you can just navigate to the store normally. Also, make sure you run the install.bat first and not accidentally run one of the .sh files.

**Comment by rupeshs** [comment]
@KintCark  @Dog66609  Please refer this  https://youtu.be/8uoPPKXHM-A
