### ISSUE TITLE
Lora models how do we apply them to image?

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#175]
I'm trying to use an sbxl turbo lora but it's not working how do I use loras in the app? Does lcm mode have lora model support?

**Comment by rupeshs** [comment]
@KintCark SDXL turbo model is not compatible with Lora, avoid using turbo models with LoRA
Checkout this tutorial on "How to use LoRA models with FastSD CPU" https://youtu.be/N_LUxd6G2nk
