### ISSUE TITLE
Error in dependencies python during first launch, win11

### ISSUE THREAD

**Issue by Alcore01** [rupeshs/fastsdcpu#181]
Starting fastsdcpu...
Python command check :OK
Python version: 3.11.9
Traceback (most recent call last):
  File "C:\stable\fastsdcpu-1.0.0-beta.30\\src\app.py", line 5, in <module>
    from backend.controlnet import controlnet_settings_from_dict
  File "C:\stable\fastsdcpu-1.0.0-beta.30\src\backend\controlnet.py", line 3, in <module>
    from diffusers import ControlNetModel
  File "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\diffusers\utils\__init__.py", line 90, in <module>
    from .peft_utils import (
  File "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\diffusers\utils\peft_utils.py", line 27, in <module>
    import torch
  File "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by rupeshs** [comment]
@Alcore01 Please install Visual C++ Redistributable for Visual Studio 2015, restart PC, and try again .
Download: https://www.microsoft.com/en-in/download/details.aspx?id=48145

**Comment by Alcore01** [comment]
thank you for your reply, it seem that it is not yet solved : ServicePackLevel >= 1)' evaluates to true.
[1F40:14D4][2024-05-10T21:14:16]i199: Detect complete, result: 0x0
[1F40:313C][2024-05-10T21:14:20]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

**Comment by anarain86** [comment]
I am getting the same issue he is having. I can't run the program because of it.

> thank you for your reply, it seem that it is not yet solved : ServicePackLevel >= 1)' evaluates to true. [1F40:14D4][2024-05-10T21:14:16]i199: Detect complete, result: 0x0 [1F40:313C][2024-05-10T21:14:20]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

**Comment by arifbomber** [comment]
I'm getting the same problem, windows 10 python 3.11.6

> Starting fastsdcpu... Python command check :OK Python version: 3.11.9 Traceback (most recent call last): File "C:\stable\fastsdcpu-1.0.0-beta.30\src\app.py", line 5, in from backend.controlnet import controlnet_settings_from_dict File "C:\stable\fastsdcpu-1.0.0-beta.30\src\backend\controlnet.py", line 3, in from diffusers import ControlNetModel File "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\diffusers__init__.py", line 5, in from .utils import ( File "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\diffusers\utils__init__.py", line 90, in from .peft_utils import ( File "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\diffusers\utils\peft_utils.py", line 27, in import torch File "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\torch__init__.py", line 141, in raise err OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\stable\fastsdcpu-1.0.0-beta.30\env\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by eNerGy33** [comment]
Good afternoon. How were you able to solve this problem? VS installed. Python 3.11.6
![изображение_2024-08-05_132811229](https://github.com/user-attachments/assets/a95a8bbd-eac7-4d8a-b26c-9ebb6376aeac)

**Comment by anarain86** [comment]
I think I was able to fix the problem. If you still have the problem after installing the c++ redistribute, you will need [Lucasg Dependencies walker]()https://github.com/lucasg/Dependencies/releases to see if fbgemm.dll is missing some other dependency. Usually it happens to be libomp140.x86_64.dll.  You can get that [here](https://www.dllme.com/dll/files/libomp140_x86_64?sort=upload&arch=0x8664)

**Comment by rupeshs** [comment]
@eNerGy33  Please check this discussion https://github.com/rupeshs/fastsdcpu/discussions/237
