### ISSUE TITLE
Not opening Web-ui and desktop

### ISSUE THREAD

**Issue by AlgorithmicKing** [rupeshs/fastsdcpu#182]
https://github.com/rupeshs/fastsdcpu/assets/147901320/2efb8c1f-dc1a-46d2-975b-ce0921c3e192

**Comment by rupeshs** [comment]
Can you run it from command prompt.Open command prompt and type install.bat inside the fastsdcpu folder

**Comment by rupeshs** [comment]
Thanks for using FastSD

**Comment by AlgorithmicKing** [comment]
still havent figured out how you do it so fast. AI?
