### ISSUE TITLE
RealVisXL v4.0 not generating images properly

### ISSUE THREAD

**Issue by AlgorithmicKing** [rupeshs/fastsdcpu#184]
![3de61218-7233-405d-abf7-afbb94eba64e-1](https://github.com/rupeshs/fastsdcpu/assets/147901320/36991008-728b-4717-b8a3-631b3febc261)
this is the image that it generated and it generates it every time I try to generate the image

**Comment by AlgorithmicKing** [comment]
well now it generates an image (after changing the interference steps to 25 or max value) but the images look extremely bad according to https://imgsys.org/ RealVisXL v4.0 is the best open source image model. here are the images that it generated
prompt = nature landscape
![f6a6256d-7992-47ac-973a-82fbb1845554-1](https://github.com/rupeshs/fastsdcpu/assets/147901320/928ef371-e3b1-4358-81e8-c99d2d0d64e7)
prompt = nature landscape or fantasy landscape i dont remember
![4728a4a2-843f-46b8-95f7-0fadf4708328-1](https://github.com/rupeshs/fastsdcpu/assets/147901320/57afb81e-cae5-4a3a-8e76-7d135f18080a)

**Comment by AlgorithmicKing** [comment]
prompt = the moon, size = 
![Uploading e2742b39-7cbc-470f-8fb7-6af0000ea1fd-1.png…]()
512 512

**Comment by AlgorithmicKing** [comment]
same prompt same size
![7594ae6f-499f-4d50-bdb4-909d1bef6ab1-1](https://github.com/rupeshs/fastsdcpu/assets/147901320/0d84f324-ca3b-4f73-a211-5eabc5d14692)

**Comment by rupeshs** [comment]
@AlgorithmicKing Able to generate image without any issue.

**Comment by rupeshs** [comment]
@AlgorithmicKing  Follow the config, image size 768 x 768, steps 3
Mode - LCM-LoRa select LCM-Lora model as latent-consistency/lcm-lora-sdxl
![image](https://github.com/rupeshs/fastsdcpu/assets/3255994/b3c59637-7100-4895-bacc-a92270db800f)

**Comment by AlgorithmicKing** [comment]
how do i set the lcm lora model to SG161222/RealVisXL_V4.0? i dont see the option

**Comment by rupeshs** [comment]
@AlgorithmicKing update stable-diffusion-models.txt
Also refer : https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#models 
![image](https://github.com/rupeshs/fastsdcpu/assets/3255994/d7f0539a-91ff-4c85-accc-9a7f5ee6bd9a)

**Comment by AlgorithmicKing** [comment]
thanks a lot

**Comment by AlgorithmicKing** [comment]
1. also how did you know to set those specific configuration where did you get where can i get it for other models?

**Comment by rupeshs** [comment]
@AlgorithmicKing please checkout readme it has lots of details for you.
