### ISSUE TITLE
fastsdcpu offline?

### ISSUE THREAD

**Issue by bjivanovich** [rupeshs/fastsdcpu#190]
I want to know if there's a way to use fastsdcpu offline.
How can i use the models I have on A1111/models/StableDiffusion folder on my PC
I will convert the models into OpenVINO models follown de scrits.
Should I modify stable-diffusion-models.txt or settings.yaml?
The models are located in D:/A1111/models/StableDiffusion
I'm new on Stable Diffusion, need help and step by step instruction

**Comment by rupeshs** [comment]
@bjivanovich  Thanks for using FastSD CPU, enable this setting
Checkout this https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#models
![image](https://github.com/rupeshs/fastsdcpu/assets/3255994/ad2d7e05-80bc-447f-b064-aae6a6cbca21)

**Comment by rupeshs** [comment]
@bjivanovich LCM-LoRA offline tutorial  https://www.youtube.com/watch?v=T8kZL5l3K8c
