### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by ProtoBelisarius** [rupeshs/fastsdcpu#195]
I get the following output from start.sh or start-webui.sh:

```
Starting FastSD CPU please wait...
Found python command
Python version : 3.10.14
/home/USER/Git/fastsdcpu/src/app.py:223: SyntaxWarning: invalid escape sequence '\l'
  help="LoRA model full path e.g D:\lora_models\CuteCartoon15V-LiberteRedmodModel-Cartoon-CuteCartoonAF.safetensors",
Traceback (most recent call last):
  File "/home/USER/Git/fastsdcpu/src/app.py", line 5, in <module>
    from backend.controlnet import controlnet_settings_from_dict
  File "/home/USER/Git/fastsdcpu/src/backend/controlnet.py", line 2, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```
Im on linux and Ive cloned it, made a python 3.10 venv and installed the requirements.

**Comment by ivan-robic** [comment]
Got this error on Linux Mint with Python 3.10.12.
After removing virtual environment and rebooting system, then creating new venv it worked.

**Comment by rupeshs** [comment]
@ProtoBelisarius  Please do a reinstall.

**Comment by ruberkel** [comment]
Win11 here. I get the same error after installation. installation says "ERROR: Could not find a version that satisfies the requirement openvino==2024.0.0 (from versions: 2024.1.0)
ERROR: No matching distribution found for openvino==2024.0.0" and then start.bat throws the error on this thread. using python 3.12.4.

**Comment by rupeshs** [comment]
> Win11 here. I get the same error after installation. installation says "ERROR: Could not find a version that satisfies the requirement openvino==2024.0.0 (from versions: 2024.1.0) ERROR: No matching distribution found for openvino==2024.0.0" and then start.bat throws the error on this thread. using python 3.12.4.

Please use Python 3.11.6,

**Comment by ruberkel** [comment]
> > 
> 
> @ruberkel Please use Python 3.11.6

It works! Thanks!
