### ISSUE TITLE
[BUG]Hardrive somehow run out disk to 0 byte 

### ISSUE THREAD

**Issue by tukangcode** [rupeshs/fastsdcpu#196]
how repeat it
OS : windows 10 proffesional
hardisk : hynix 238,47
Ram : 20 gb
do some edit related to this issue : https://github.com/rupeshs/fastsdcpu/discussions/137#discussioncomment-8453953
run instal.bat
succes
do some edit related to this issue : https://github.com/rupeshs/fastsdcpu/discussions/137#discussioncomment-8453953 to webuit and star.bat

run webui.bat
download some model
waiting
run out disk warning.
0 byte left on disk D.

**Comment by tukangcode** [comment]
what minimun disk for instal lcm stable diffusion ? and why it download slow and sometime frozen ?

**Comment by tukangcode** [comment]
nvm find again solution for slow download
1. Clone the Hugging Face module repository using `git clone`. Wait until the process is complete or crashes, then close the terminal.
2. Download the safetensor module manually and place it in the appropriate folders one by one (refer to the Hugging Face module page for folder details).
3. Follow the configuration settings to load the local module.
4. Open `start.bat` or `webui`.
5. Done.
Note: The average size of each module is 10 GB, so ensure you have enough disk space.

**Comment by rupeshs** [comment]
@tukangcode Glad that it is working
