### ISSUE TITLE
OS Error when using offline cached models

### ISSUE THREAD

**Issue by khanumballz** [rupeshs/fastsdcpu#198]
```
OSError: Error no file named diffusion_pytorch_model.bin found in directory /home/khan/.cache/huggingface/hub/models--prompthero--openjourney-v4/snapshots/b195ed2d503f3eb29637050a886d77bd81d35f0e/vae.
```

No idea what's going on, but the offline feature does not work yet.

**Comment by khanumballz** [comment]
Fixed it by downloading the model again, and then setting the offline option again - but the error appears again after 24 hours and all my models keep disappearing?

**Comment by khanumballz** [comment]
I think I have a better idea of what's going on.

When setting guidance scale to more than > 1.0 -- an entire new model is going to be downloaded and used.

I will confirm tomorrow see if there's any more issues now that I (think I) have downloaded all the models I need. 

```
ls(base) khan@khan-desktop:~/.cache/huggingface/hub$ ls
models--latent-consistency--lcm-lora-sdv1-5  models--stabilityai--sd-turbo
models--Lykon--dreamshaper-8                 version_diffusers_cache.txt
models--prompthero--openjourney-v4           version.txt
```

**Comment by rupeshs** [comment]
@khanumballz  Follow this tutorial https://www.youtube.com/watch?v=T8kZL5l3K8c
