### ISSUE TITLE
LCM-LORA CRASH

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#200]
I'm using this on Termux Android I got 12gb of ram but lcm-lora sdxl 1.0 crashes termux when in the beginning of processing. I even tried small encoder and it still crashed I have more than enough ram. Lcm mode works fine tho but I'm trying to use midjourney mimic lora but I'm confused on how to make it work I think I need sdxl 1.0 not sdxl lcm it should work for any model.

**Comment by KintCark** [comment]
I'm trying to add sd1.5 models to fastsdcpu but I'm confused on what termux file path is supposed to make it work. I put /root/fastsdcpu/sd15/xenoplastyBimbosBoobs_lcmV1.safetensors

But it not working

**Comment by KintCark** [comment]
Darn I read and it say it's only works in lcm-lora mode but that mode doesn't work for me:( how can we add more models for lcm mode not lcm-lora mode.

**Comment by KintCark** [comment]
OK I finally figured out how to install safetensors, but I'm getting this error 

latent-consistency/lcm-lora-sdv1-5 does not appear to have a file named pytorch_lora_weights.safetensors

**Comment by KintCark** [comment]
OK I finally figured out how to install safetensors, but I'm getting this error 

latent-consistency/lcm-lora-sdv1-5 does not appear to have a file named pytorch_lora_weights.safetensors

**Comment by KintCark** [comment]
OK I finally figured out how to install safetensors, but I'm getting this error 

latent-consistency/lcm-lora-sdv1-5 does not appear to have a file named pytorch_lora_weights.safetensors



Lcm-lora crashes with sd1.5 model as well idk what's wrong diffusers models are 10.3gb!! So it should work with the sdxl sd15 models.

**Comment by KintCark** [comment]
Looks like the other lora did the same thing


OSError: rupeshs/hypersd-sd1-5-1-step-lora does not appear to have a file named pytorch_lora_weights.safetensors.

**Comment by KintCark** [comment]
BTW if anyone wanna know how to add correct path to termux its: /root/fastsdcpu/YOUR FILE NAME/toonBabes_v10.safetensors

**Comment by rupeshs** [comment]
CFG scale upate here https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.33
