### ISSUE TITLE
How to add lcm models? I think I figured it out!?

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#204]
Uhh I think to add lcm mode models we gotta use diffusers but does it have to have the diffusers model or can it just be the model json,unet,shedular,text_encoder,Vae_decoder/endoder, etc..... folders I hope I'm correct 💯💪 please answer this question as soon as possible I'll be waiting:)

**Comment by KintCark** [comment]
Yyyyyeeeeaaahh!!!! Lcm mode needs diffusers format I trying open journey but 256x256 give glitched jumbled image I'ma try 512x512. Thx man!!!

**Comment by rupeshs** [comment]
@KintCark also please follow this tutorial https://www.youtube.com/watch?v=N_LUxd6G2nk
please subscribe

**Comment by KintCark** [comment]
Hey please add higher cfg guidance scale cuz you can use non lcm diffusers in lcm mode I try open journey but the image was cloudy please enable cfg guidance in lcm mode pleassee

**Comment by rupeshs** [comment]
@KintCark sure,will add higher cfg support in the next release

**Comment by rupeshs** [comment]
@KintCark could you please create new feature request for cfg? closing this ticket
