### ISSUE TITLE
Higher cfg guidance 

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#205]
Hey you can add non lcm diffusers to lcm mode I tried openjourney but the image was cloudy. We need the maxed cfg guidance scale for lcm mode please add cfg higher scale at least cfg 0.1-10.0 please make cfg available for lcm mode lcm lora mode also thx 😊 🙏

**Comment by KintCark** [comment]
Btw when u update the app does the app automatically update itself? Or do I have to reinstall in termux?

**Comment by rupeshs** [comment]
@KintCark You need to reinstall FastSD CPU, I will probably release it by tomorrow.

**Comment by KintCark** [comment]
OK ima still test it out but I'm using automatic 1111

**Comment by rupeshs** [comment]
@KintCark  Added in the latest release https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.33
