### ISSUE TITLE
Longer token prompts and negative

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#207]
Hey I got another idea please add 150 token limit I noticed it caps at 77 but it would be nice if we could make longer prompts. Also add negative prompt feature for lcm mode

**Comment by rupeshs** [comment]
@KintCark The Current token limit is 77.
Regarding negative prompts in LCM mode use a guidance scale greater than 1 ( Please note that (guidance scale >1) memory usage will increase and image generation will become slower)

**Comment by KintCark** [comment]
> @KintCark The Current token limit is 77.
> Regarding negative prompts in LCM mode use a guidance scale greater than 1 ( Please note that (guidance scale >1) memory usage will increase and image generation will become slower)

But when I did that in the console it says: not using lcm-lora mode setting guidance scale to 1.0 it automatically sets the scale back to 1 if I'm not using lcm-lora mode?

Please help me understand that sentence 🙏

**Comment by rupeshs** [comment]
@KintCark Negative prompt only works in the LCM Lora mode (See the screenshot)
![image](https://github.com/rupeshs/fastsdcpu/assets/3255994/261fbd4f-fa32-40cf-9647-5fe891e919ed)

**Comment by rupeshs** [comment]
longer prompt support duplicate #28
