### ISSUE TITLE
I fixed lcm-lora!!!

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#208]
Hey its working now I removed all the lcm-lora Loras and then tried dream shaper8 I removed all the models out the configuration and am adding custom ones but I'm trying to use a sdxl model from Civitai but it automatically downloaded dreamshaper model maybe I gota put the file path back can u give me the configuration files do I can put back the lcm-lora paths I don't want to reinstall the whole thing.

**Comment by KintCark** [comment]
The lcm-lora loras where breaking lcm-lora mode

**Comment by KintCark** [comment]
The lcm-lora loras where breaking lcm-lora mode



Srry I lied the only reason lcm-lora worked on Android is because the dreamshaper mod r l is not 7gb I can't for some reason load 7gb models, but 10gb Diffusers work fine but not safetensors ima test the realvisionxl4 diffuser if it don't work then it's just sdxl that doesn't work on termux.

**Comment by rupeshs** [comment]
@KintCark Hope your issue solved closing this issue.
