### ISSUE TITLE
fp16 safetensors support ?

### ISSUE THREAD

**Issue by Amin456789** [rupeshs/fastsdcpu#21]
HI!
in huggingface there is a safetensors file of the normal model [not openvino], can u guys add safetensor support please?

as i can see u support offline and we can choose model so i though maybe we can get that safetensor instead now
it will be great if we can a fp16 support too, there is a model converter in sd webui automatic1111 that we can use to convert to fp16 maybe

**Comment by rupeshs** [comment]
@Amin456789  For fp16 is not supported on CPU , CPUs use high precision float32 data
