### ISSUE TITLE
Using separately downloaded 6GB checkpoint models?

### ISSUE THREAD

**Issue by AlgorithmicKing** [rupeshs/fastsdcpu#212]
Is there a way to use separately downloaded 6GB checkpoint models instead of downloaded 12GB models from the web UI? for example for ComfyUI you download the 6GB models and place them in the checkpoints folder.

**Comment by rupeshs** [comment]
@AlgorithmicKing  Try this: https://youtu.be/zZTfUZnXJVk

**Comment by AlgorithmicKing** [comment]
thanks a lot 💐💐💐👍👍
