### ISSUE TITLE
Sd 2.1.768 support?

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#213]
Will u add stable diffusion 2.1.768 support cause I wanna use ffusionai model the best one is on sd2.1768 but idk if my phone can load 5gb models

Leaving cfg on 1.0 used less ram that's y lcm-mode crashes cus I had it on 2.0 or 1.5 now I can use sd1.5 models even 4gb models work!!

**Comment by rupeshs** [comment]
I suggest SD 1.5 models for phones since it is memory efficient.
