### ISSUE TITLE
Command args?

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#216]
Hey are there any command arms we can use like lowvram split attention no half etc.....?

**Comment by KintCark** [comment]
I just realized only sd 1.5 single file safetensors are supported that's y it was crashing....will sdxl Safetensors be supported soon?

**Comment by rupeshs** [comment]
> I just realized only sd 1.5 single file safetensors are supported that's y it was crashing....will sdxl Safetensors be supported soon?

Not soon, may be later

**Comment by rupeshs** [comment]
> Hey are there any command arms we can use like lowvram split attention no half etc.....?
FastSD CPU is current focus is on CPU. VRAM does not come into the picture now.
