### ISSUE TITLE
None lora selection 

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#218]
Please add an none option for the lora selection higher cfg needs this using higher cfg with an lora makes burnt messy images

**Comment by rupeshs** [comment]
In LCM-LoRA mode you must provide the LCM-Lora model ( It will generate image CFG <=1 ). If you are using a negative prompt then a higher CFG needed.(It already documented in the readme)

https://github.com/rupeshs/fastsdcpu/blob/3ca4554831ef5437d9c41c0f75a8af8ca2b28fc7/configs/lcm-lora-models.txt#L1

**Comment by KintCark** [comment]
Oh but when putting the cfg to 5 with a negative prompt it creates a burnt image.
Maybe u could add an non lora mode where we can use single file safetensors without lora lcm like a non lcm. Tab for original models.if u understand what I'm trying to say:)

**Comment by rupeshs** [comment]
Original models needs 20 to 50 steps to generate  an image (slow).Original models use CFG 7.5 or higher but it will make image generation process slow.
