### ISSUE TITLE
Model 

### ISSUE THREAD

**Issue by redflagrul** [rupeshs/fastsdcpu#23]
Could you tell me we're I can set my model at an how to load would like to use a realistic model from civiai

**Comment by Amin456789** [comment]
i dont think u can for now, it seems it uses its specific model, they trained this dreamshaper so we have to wait they release training code or something so people make new models

**Comment by rupeshs** [comment]
More model support will be added in the future, currently available models  https://github.com/rupeshs/fastsdcpu#lcm-models
