### ISSUE TITLE
FLUX!!!! PLEASE!!!!

### ISSUE THREAD

**Issue by KintCark** [rupeshs/fastsdcpu#230]
CAN you please add Flux and Sd3 And Pixart Sigma900!!!!??? ProteusV5,Open dalev1.1,Mobius,Model one,Playgroundv2.5,Prometheus,ProteusV4 Lightning!!!???

**Comment by rupeshs** [comment]
@KintCark  Checkout latest release: https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.36

**Comment by KintCark** [comment]
> @KintCark  Checkout latest release: https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.36

Hey I need gguf support I'm currently able to use flux on comfyui,is it possible to use gguf models?

**Comment by KintCark** [comment]
Yeah I'm not able to use openvino I don't have enough ram I can't use that thx for adding it but I'll stick with comfyui for now
