### ISSUE TITLE
Long processing with libomp140.x86_64.dll

### ISSUE THREAD

**Issue by eNerGy33** [rupeshs/fastsdcpu#247]
Good afternoon.
I have fastsd_beta_32 installed on another PC. It does not require libomp140.x86_64.dll. The image generation speed is much higher. Dreamshaper_v8 model, 3 steps, 512x512 takes ~15 seconds (i5-1235U). And on new builds where this library is needed, it now requires 8-9 seconds for each stage and after that it hangs for a very long time ~20 seconds, which comes out to ~50 seconds per image! Can you post a build that worked without this library?

![IMG_20240825_172342](https://github.com/user-attachments/assets/2f108d1f-ab7f-4dfd-86b1-0e72f7e7c2f5)

**Comment by eNerGy33** [comment]
Thank you very much for removing this library in version 53. Now the image creation speed takes 20 seconds with the same model settings.
<img width="767" alt="11" src="https://github.com/user-attachments/assets/bce2fd87-84dc-4bcd-a471-1f889bb8a83b">

**Comment by rupeshs** [comment]
Resolved in the release https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.53
