### ISSUE TITLE
Qt GUI version not working on Linux?

### ISSUE THREAD

**Issue by monstruosoft** [rupeshs/fastsdcpu#257]
I can't seem to be able to run the Qt GUI in the most recent FastSD CPU version on Linux. I made some tests and found that the Qt version in commit _a8cafa1_ works fine but it stops working in the next commit, _7e35f97_, but there doesn't seem to be any Qt related changes in that commit so I can't tell if it's an issue on my machine. Can someone confirm?.

Thanks.

**Comment by monstruosoft** [comment]
Nevermind, this seems to be a common problem related to the _opencv-python_ package, solved it by removing _opencv-python_ and installing _opencv-python-headless_ instead as suggested in some of the available answers.

**Comment by rupeshs** [comment]
closing this
