### ISSUE TITLE
How do I use 100% offline?

### ISSUE THREAD

**Issue by sysmaya** [rupeshs/fastsdcpu#266]
Every time I start the program a download of several Gigs begins.
The correct thing is to turn on the program and use. Turn on the program and wait more than 2 hours for it to update... every time it turns on...
Is there a way to disable updates.

**Comment by rupeshs** [comment]
@sysmaya Please enable this setting.
![image](https://github.com/user-attachments/assets/192b9afa-2305-4d02-bede-669a1c1c1533)

Also check this : https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#how-to-use-lcm-lora-models-offline
