### ISSUE TITLE
【help help kid】OSError: [WinError -1073741795] Windows Error 0xc000001d

### ISSUE THREAD

**Issue by SakuraMaiii** [rupeshs/fastsdcpu#267]
THANKS FOR YOUR GREAT JOB!

```
GGUF Threads : 2
GGUF - Model config
{'clip_path': 'D:\\Py_project\\sd\\models\\gguf\\clip\\clip_l_q4_0.gguf',
 'diffusion_path': 'D:\\Py_project\\sd\\models\\gguf\\diffusion\\flux1-schnell-q4_0.gguf',
 'gguf_models': 'D:\\pyproject\\sd\\models\\gguf',
 't5xxl_path': 'D:\\Py_project\\sd\\models\\gguf\\t5xxl\\t5xxl_q4_0.gguf',
 'vae_path': 'D:\\Py_project\\sd\\models\\gguf\\vae\\ae.safetensors'}
GGUF Diffusion on Windows
Traceback (most recent call last):
  File "D:\Py_project\sd\src\frontend\gui\image_generator_worker.py", line 29, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Py_project\sd\src\frontend\gui\app_window.py", line 595, in generate_image
    images = self.context.generate_text_to_image(
  File "D:\Py_project\sd\src\context.py", line 56, in generate_text_to_image
    self.lcm_text_to_image.init(device, settings.lcm_diffusion_setting)
  File "D:\Py_project\sd\src\backend\lcm_text_to_image.py", line 275, in init
    self._init_gguf_diffusion(lcm_diffusion_setting)
  File "D:\Py_project\sd\src\backend\lcm_text_to_image.py", line 545, in _init_gguf_diffusion
    self.pipeline = GGUFDiffusion(
  File "D:\Py_project\sd\src\backend\gguf\gguf_diffusion.py", line 146, in __init__
    self.sd_ctx = self.libsdcpp.new_sd_ctx(
OSError: [WinError -1073741795] Windows Error 0xc000001d
```

Here is my computer configuration: 
Intel(R) Celeron(R) N5095 @ 2.00GHz 2.00 GHz 
64-bit operating system 
16GB RAM

**Comment by rupeshs** [comment]
@SakuraMaiii  Thanks,are you able to run other modes, LCM/LCM-LoRA or LCM - OpenVINO? From the logs `GGUF Threads : 2` it will be very very slow to run Flux on this CPU. Please try other models.

**Comment by SakuraMaiii** [comment]
> Thanks,are you able to run other modes, LCM/LCM-LoRA or LCM - OpenVINO? From the logs `GGUF Threads : 2` it will be very very slow to run Flux on this CPU. Please try other models. The sd-turbo is a good starting point.

Thanks! I can run LCM/LCM LoRA,but LCM - OpenVINO like this：
```
Fetching 19 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<?, ?it/s]
Compiling the vae_decoder to CPU ...
Compiling the unet to CPU ...
Compiling the vae_encoder to CPU ...
Compiling the text_encoder to CPU ...
Traceback (most recent call last):
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\Py_project\sd\src\frontend\webui\text_to_image_ui.py", line 54, in generate_text_to_image
    images = future.result()
  File "D:\Software\Anaconda\envs\sd\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "D:\Software\Anaconda\envs\sd\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\Software\Anaconda\envs\sd\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Py_project\sd\src\context.py", line 56, in generate_text_to_image
    self.lcm_text_to_image.init(device, settings.lcm_diffusion_setting)
  File "D:\Py_project\sd\src\backend\lcm_text_to_image.py", line 250, in init
    self.pipeline = get_ov_text_to_image_pipeline(
  File "D:\Py_project\sd\src\backend\openvino\pipelines.py", line 47, in get_ov_text_to_image_pipeline
    pipeline = OVStableDiffusionPipeline.from_pretrained(
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\modeling_base.py", line 420, in from_pretrained
    return from_pretrained_method(
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 336, in _from_pretrained
    return cls(
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 165, in __init__
    self.compile()
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 589, in compile
    component._compile()
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 634, in _compile
    self.request = core.compile_model(self.model, self._device, self.ov_config)
  File "D:\Software\Anaconda\envs\sd\lib\site-packages\openvino\runtime\ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src\inference\src\cpp\core.cpp:107:
Exception from src\inference\src\dev\plugin.cpp:53:
Check '(std::find(in_idxs.begin(), in_idxs.end(), idx) == in_idxs.end())' failed at src\plugins\intel_cpu\src\emitters\plugin\x64\jit_emitter.cpp:76:
ov::intel_cpu::jit_emitter: Xmm(0) cannot be input register in SSE41
```
I would like to ask for your advice. Is it because my computer's configuration is too low, or is it because the stable_diffusion.dll does not have the instruction set? I don't quite understand why the error occurs.

**Comment by rupeshs** [comment]
> > Thanks,are you able to run other modes, LCM/LCM-LoRA or LCM - OpenVINO? From the logs `GGUF Threads : 2` it will be very very slow to run Flux on this CPU. Please try other models. The sd-turbo is a good starting point.
> 
> Thanks! I can run LCM/LCM LoRA,but LCM - OpenVINO like this：
> 
> ```
> Fetching 19 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<?, ?it/s]
> Compiling the vae_decoder to CPU ...
> Compiling the unet to CPU ...
> Compiling the vae_encoder to CPU ...
> Compiling the text_encoder to CPU ...
> Traceback (most recent call last):
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\queueing.py", line 536, in process_events
>     response = await route_utils.call_process_api(
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\blocks.py", line 1935, in process_api
>     result = await self.call_function(
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\blocks.py", line 1520, in call_function
>     prediction = await anyio.to_thread.run_sync(  # type: ignore
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
>     return await get_async_backend().run_sync_in_worker_thread(
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
>     return await future
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
>     result = context.run(func, *args)
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\utils.py", line 826, in wrapper
>     response = f(*args, **kwargs)
>   File "D:\Py_project\sd\src\frontend\webui\text_to_image_ui.py", line 54, in generate_text_to_image
>     images = future.result()
>   File "D:\Software\Anaconda\envs\sd\lib\concurrent\futures\_base.py", line 458, in result
>     return self.__get_result()
>   File "D:\Software\Anaconda\envs\sd\lib\concurrent\futures\_base.py", line 403, in __get_result
>     raise self._exception
>   File "D:\Software\Anaconda\envs\sd\lib\concurrent\futures\thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "D:\Py_project\sd\src\context.py", line 56, in generate_text_to_image
>     self.lcm_text_to_image.init(device, settings.lcm_diffusion_setting)
>   File "D:\Py_project\sd\src\backend\lcm_text_to_image.py", line 250, in init
>     self.pipeline = get_ov_text_to_image_pipeline(
>   File "D:\Py_project\sd\src\backend\openvino\pipelines.py", line 47, in get_ov_text_to_image_pipeline
>     pipeline = OVStableDiffusionPipeline.from_pretrained(
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\modeling_base.py", line 420, in from_pretrained
>     return from_pretrained_method(
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 336, in _from_pretrained
>     return cls(
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 165, in __init__
>     self.compile()
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 589, in compile
>     component._compile()
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 634, in _compile
>     self.request = core.compile_model(self.model, self._device, self.ov_config)
>   File "D:\Software\Anaconda\envs\sd\lib\site-packages\openvino\runtime\ie_api.py", line 543, in compile_model
>     super().compile_model(model, device_name, {} if config is None else config),
> RuntimeError: Exception from src\inference\src\cpp\core.cpp:107:
> Exception from src\inference\src\dev\plugin.cpp:53:
> Check '(std::find(in_idxs.begin(), in_idxs.end(), idx) == in_idxs.end())' failed at src\plugins\intel_cpu\src\emitters\plugin\x64\jit_emitter.cpp:76:
> ov::intel_cpu::jit_emitter: Xmm(0) cannot be input register in SSE41
> ```
> 
> I would like to ask for your advice. Is it because my computer's configuration is too low, or is it because the stable_diffusion.dll does not have the instruction set? I don't quite understand why the error occurs.

Two points to note here 
- Flux requires powerful CPU
- Your CPU not supported some SSE instructions used by stablediffusion.dll, you can manully build stablediffusion in your PC and use it,follow this steps https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#build-stablediffusioncpp-shared-library-for-gguf-flux-model-supportoptional

**Comment by SakuraMaiii** [comment]
> > > Thanks,are you able to run other modes, LCM/LCM-LoRA or LCM - OpenVINO? From the logs `GGUF Threads : 2` it will be very very slow to run Flux on this CPU. Please try other models. The sd-turbo is a good starting point.
> > 
> > 
> > Thanks! I can run LCM/LCM LoRA,but LCM - OpenVINO like this：
> > ```
> > Fetching 19 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<?, ?it/s]
> > Compiling the vae_decoder to CPU ...
> > Compiling the unet to CPU ...
> > Compiling the vae_encoder to CPU ...
> > Compiling the text_encoder to CPU ...
> > Traceback (most recent call last):
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\queueing.py", line 536, in process_events
> >     response = await route_utils.call_process_api(
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
> >     output = await app.get_blocks().process_api(
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\blocks.py", line 1935, in process_api
> >     result = await self.call_function(
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\blocks.py", line 1520, in call_function
> >     prediction = await anyio.to_thread.run_sync(  # type: ignore
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
> >     return await get_async_backend().run_sync_in_worker_thread(
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
> >     return await future
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
> >     result = context.run(func, *args)
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\gradio\utils.py", line 826, in wrapper
> >     response = f(*args, **kwargs)
> >   File "D:\Py_project\sd\src\frontend\webui\text_to_image_ui.py", line 54, in generate_text_to_image
> >     images = future.result()
> >   File "D:\Software\Anaconda\envs\sd\lib\concurrent\futures\_base.py", line 458, in result
> >     return self.__get_result()
> >   File "D:\Software\Anaconda\envs\sd\lib\concurrent\futures\_base.py", line 403, in __get_result
> >     raise self._exception
> >   File "D:\Software\Anaconda\envs\sd\lib\concurrent\futures\thread.py", line 58, in run
> >     result = self.fn(*self.args, **self.kwargs)
> >   File "D:\Py_project\sd\src\context.py", line 56, in generate_text_to_image
> >     self.lcm_text_to_image.init(device, settings.lcm_diffusion_setting)
> >   File "D:\Py_project\sd\src\backend\lcm_text_to_image.py", line 250, in init
> >     self.pipeline = get_ov_text_to_image_pipeline(
> >   File "D:\Py_project\sd\src\backend\openvino\pipelines.py", line 47, in get_ov_text_to_image_pipeline
> >     pipeline = OVStableDiffusionPipeline.from_pretrained(
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\modeling_base.py", line 420, in from_pretrained
> >     return from_pretrained_method(
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 336, in _from_pretrained
> >     return cls(
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 165, in __init__
> >     self.compile()
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 589, in compile
> >     component._compile()
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 634, in _compile
> >     self.request = core.compile_model(self.model, self._device, self.ov_config)
> >   File "D:\Software\Anaconda\envs\sd\lib\site-packages\openvino\runtime\ie_api.py", line 543, in compile_model
> >     super().compile_model(model, device_name, {} if config is None else config),
> > RuntimeError: Exception from src\inference\src\cpp\core.cpp:107:
> > Exception from src\inference\src\dev\plugin.cpp:53:
> > Check '(std::find(in_idxs.begin(), in_idxs.end(), idx) == in_idxs.end())' failed at src\plugins\intel_cpu\src\emitters\plugin\x64\jit_emitter.cpp:76:
> > ov::intel_cpu::jit_emitter: Xmm(0) cannot be input register in SSE41
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would like to ask for your advice. Is it because my computer's configuration is too low, or is it because the stable_diffusion.dll does not have the instruction set? I don't quite understand why the error occurs.
> 
> Two points to note here
> 
> * Flux requires powerful CPU
> * Your CPU not supported some SSE instructions used by stablediffusion.dll, you can manully build stablediffusion,dll in your PC and use it,follow this steps https://github.com/rupeshs/fastsdcpu?tab=readme-ov-file#build-stablediffusioncpp-shared-library-for-gguf-flux-model-supportoptional

Thanks！ I will try
