### ISSUE TITLE
Troubles with running android installation 

### ISSUE THREAD

**Issue by misfit-mischief** [rupeshs/fastsdcpu#272]
I have followed patienx step by step guide for installing on android and all goes well,  until I try to run it. 

AttributeError: module 'timm.models._registry' has no attribute 'get_pretrained_cfgs_for_arch'. Did you mean: 'get_pretrained_cfg_value'?

This is the error I keep getting. Any advice is appreciated.

**Comment by misfit-mischief** [comment]
I tried that as well but it fails to even install with this method. Something about not being able to find mediapipe 0.10.9

**Comment by rupeshs** [comment]
> I tried that as well but it fails to even install with this method. Something about not being able to find mediapipe 0.10.9

Ensure that you are using python 3.11.

**Comment by misfit-mischief** [comment]
Ok I checked and it is python 3.12 and no 3.11 found when I search with apt. This time around I noticed python3-distutils has no installl candidate. 

Working on downgrading python in proot, no luck so far. No worries tho, this was just to see if i could, thanks for the help.
