### ISSUE TITLE
Seems to be stuck or do I wait

### ISSUE THREAD

**Issue by redflagrul** [rupeshs/fastsdcpu#279]
![image](https://github.com/user-attachments/assets/c4c8d4b7-62fb-40be-8c12-5e78f594eac1)

**Comment by redflagrul** [comment]
![image](https://github.com/user-attachments/assets/57564910-ee24-4566-8ec6-13f10f033915)

IT CAME THREW 😂

**Comment by rupeshs** [comment]
Hope it is working, yes you need to wait for the installation to complete
