### ISSUE TITLE
Only half of available threads used

### ISSUE THREAD

**Issue by veikk0** [rupeshs/fastsdcpu#36]
I'm testing this out on a Ryzen 7 3700X (8 cores 16 threads). Looking at my CPU usage, it seems that only 8 processes are spawned, and thus CPU usage is only about 50%.

Using the latest git on Linux Mint 21.2. I'm not using OpenVINO.

**Comment by rupeshs** [comment]
@veikk0  Can you try OpenVINO

**Comment by veikk0** [comment]
Same result, except that the only threads used were the last 8 threads. So apparently OpenVINO is only using a single CCD of the CPU.

I did a git pull and reinstalled to see if the latest commit made any difference, and now I'm getting [garbage output](https://github.com/rupeshs/fastsdcpu/assets/7808922/ef65ee48-ddfa-451f-89ca-67315b8dcbf8) with OpenVINO.

**Comment by rupeshs** [comment]
@veikk0 can you try a fresh install?

**Comment by deinferno** [comment]
@veikk0 I can't reproduce this bug on AMD Ryzen 3 2200G in NixOS 23.05, try recreating virtualenv.

**Comment by Amin456789** [comment]
could u guys please fix the cpu usage for the normal model [non openvino] ?

im using windows 11 and cpu usage is very very low and takes a lot of time to generate an image

**Comment by rupeshs** [comment]
@Amin456789 could you please share the following details?
Operating system :
CPU :
Time to generate 512 x 512 image in 4 steps :

**Comment by Amin456789** [comment]
cpu = intel i5-6200u
6gb ram
took 36 min for a 448x256 image but in other ui with an int8 model onnx it takes only 1 min and less sometimes, same goes with sd webui with fp16 normal models takes much much less time on ddim or euler for example

**Comment by rupeshs** [comment]
So this is modified code,sorry we can't support modified code. Please try a fresh install of FastSD CPU and feel free to raise issue. Thanks

**Comment by Amin456789** [comment]
u were right, i tested 512x512 it was 22 min which was way faster than 448x256 which was 36 min

**Comment by veikk0** [comment]
Dunno why this was closed since the CPU usage issue is still present in the latest git:

![Screenshot at 2023-10-28 19-26-43](https://github.com/rupeshs/fastsdcpu/assets/7808922/27da77f3-3c01-4800-8309-dfe6a1cb8a5d)

The garbled output I can no longer reproduce after updating to the latest git master. I also deleted the model snapshots, which may also have had something to do with it.

**Comment by rupeshs** [comment]
@veikk0 we were unable reproduce garbage output regarding half thread please check this https://github.com/openvinotoolkit/openvino/issues/14781
