### ISSUE TITLE
micromamba: command not found

### ISSUE THREAD

**Issue by hadrien-psydk** [rupeshs/fastsdcpu#4]
Hello,

I followed the installation instructions in the readme, but I cannot start the program:

```
fastsdcpu(main)$ ./start.sh 
Starting fastsdcpu please wait...
./start.sh: ligne 4: micromamba : commande introuvable
./start.sh: ligne 5: micromamba : commande introuvable
```
micromamba starts correctly if I run it directly from the terminal, but is not found within the script.
I am on Ubuntu 22.04. 

Is there something else needed to complete the installation?

**Comment by sesek3** [comment]
do u have micromamba in $PATH?

**Comment by mmh0000** [comment]
Same problem on Fedora 38.

**Comment by hadrien-psydk** [comment]
The installation script added a path that does not exist in $PATH: `.../fastsdcpu/umamba/condabin`. The executable is actually located in `.../fastsdcpu/tools/linux`

But for some reasons I was able to call `micromamba` from the terminal. This was confusing until I found out this is actually a bash function created by a script: `.../fastsdcpu/etc/profile.d/micromamba.sh`. That script is called by some lines in `.bashrc` that were added during the installation.

Maybe the bash function is not visible when running `./start.sh`

**Comment by rupeshs** [comment]
@hadrien-psydk  I am planning to release a fix for it

**Comment by redflagrul** [comment]
Install Homebrew 
Brew install micromaba
"$(SHELL)" <(curl -L micro.maba.pm/install.sh)
micromaba self-update

**Comment by rupeshs** [comment]
@hadrien-psydk  @mmh0000  Updated in the master branch, micromamba removed for UNIX env and fastsdcpu will depend on venv , could you please try again?

**Comment by hadrien-psydk** [comment]
It works now. Well done.

**Comment by rupeshs** [comment]
@hadrien-psydk  Thank you
