### ISSUE TITLE
UI doesn't scale to the size of the output image

### ISSUE THREAD

**Issue by veikk0** [rupeshs/fastsdcpu#49]
How to reproduce:

1. Run fastsdcpu on Linux (haven't tested on Windows)
2. Change width & height of generated image to 768
3. Generate image and observe that only a portion of the image is displayed in the UI.

![Screenshot at 2023-11-01 13-34-51](https://github.com/rupeshs/fastsdcpu/assets/7808922/910040e9-4862-4a67-9e81-37a4bede7771)

Actual output result:

![a746cdda-ddda-425e-9bcd-99c4286df758-1](https://github.com/rupeshs/fastsdcpu/assets/7808922/1807bef6-7a57-4167-99ce-e0986319c370)

**Comment by rupeshs** [comment]
@veikk0 It is fixed in the master branch

**Comment by veikk0** [comment]
Thanks, it works now.
