### ISSUE TITLE
Throws error in windows due to filepath containing a space

### ISSUE THREAD

**Issue by stats121** [rupeshs/fastsdcpu#5]
I assume it need quotation marks in the script to deal with the spaces. e.g. "C:\Users\Firstname Lastname\Desktop\"

**Comment by stats121** [comment]
Failed to create temp directory "C:\Users\Firstname Lastname\AppData\Local\Temp\conda-<RANDOM>\"

**Comment by stats121** [comment]
The system cannot find the file C:\Users\Firstname.
critical libmamba pip failed to install packages

**Comment by rupeshs** [comment]
Fixed path issue in the latest release beta.2
