### ISSUE TITLE
how can I only use the txt-to-image part

### ISSUE THREAD

**Issue by Y1gubigu** [rupeshs/fastsdcpu#51]
I am trying to convert speech into text and then input it into the model as an input prompt word, and then get the result (I hope to skip the GUI), but please forgive me as a novice, my programming level is really poor, when directly referencing the back-end program , it always reminds me that the corresponding module is missing

**Comment by Y1gubigu** [comment]
> It is possible,What error are you getting? Please refer src/context.py

**Comment by Y1gubigu** [comment]
> It is possible,What error are you getting? Please refer src/context.py

![image](https://github.com/rupeshs/fastsdcpu/assets/130987709/fc135956-bce1-49bf-b102-b0702ceecc7b)
I wrote a sample test , but it always prompts that this module cannot be found. What should I do to refer this.

**Comment by rupeshs** [comment]
You need to do pip -r requirements

**Comment by Y1gubigu** [comment]
> You need to do pip install -r requirements.txt

I tried it, but there are still problems later. It seems that there is something wrong with Python's import mechanism. In addition to the things that require pip, there is also something wrong with the import of other modules inside the program. I don't think I can directly reference it like this based on my ability. Maybe I should try other way, thanks for your guidance
