### ISSUE TITLE
Using GPU

### ISSUE THREAD

**Issue by jeffywilburn** [rupeshs/fastsdcpu#56]
Hi,
i have low CPU core, but i have big GPU card, how do i use this only for GPU card? my gpu rtx 4090

thanks adv.

**Comment by rupeshs** [comment]
@jeffywilburn Are you using Windows?

**Comment by jeffywilburn** [comment]
> Refe

yes, its work now, i follow disty0 
thanks sir

**Comment by noob-guy-dev** [comment]
previously in v1.0.0. beta 9 release, i was able to generate images in 4-5 seconds , without TAESD, using integrated Iris graphics (Intel - i5) , by changing device: str = "CPU" to "GPU", but now in this release , it is not working for me.

Now , device: str = "CPU" to "GPU" in both case only cpu is being used and generate image in 14+ secconds

**Comment by rupeshs** [comment]
@noob-guy-dev Please do a fresh install of the latest release v1.0.0. beta 15 https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.15
You can use iGPU by 
`set DEVICE=GPU`  - Windows
`export DEVICE=GPU` - Linux
