### ISSUE TITLE
Req: support more models + Lora support

### ISSUE THREAD

**Issue by mykeehu** [rupeshs/fastsdcpu#57]
New models have been released, and I think it will be a matter of days before new models are released after these + Lora models. I would be happy if you could support the new models and if you could choose between them.

https://huggingface.co/collections/latent-consistency/latent-consistency-models-weights-654ce61a95edd6dffccef6a8
https://huggingface.co/collections/latent-consistency/latent-consistency-models-loras-654cdd24e111e16f0865fba6

**Comment by patientx** [comment]
Instead of supporting those two models if you can somehow support using those loras (sd 1.5 and sdxl are there) and scheduler ofc, we can use any model we can provide. And that would also solve it from the root :)

**Comment by rupeshs** [comment]
WIP: Added SDXL,SSB-1B in the branch https://github.com/rupeshs/fastsdcpu/tree/add-sdxl-ssd-1b-support

**Comment by rupeshs** [comment]
Added in the release https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.12
