### ISSUE TITLE
[Feature] Add custom models for OpenVINO

### ISSUE THREAD

**Issue by Disty0** [rupeshs/fastsdcpu#61]
We can bake in the Lora, change the scheduler and convert it to OpenVINO for custom models.
But these models need a few changes in the pipeline:
  - Use OVStableDiffusionPipeline
  - Don't change the scheduler
  - Use batch size -1  for CFG == 1.0
  - We can use batch sizes if we use CFG > 1.0

Example OpenVINO space and custom model:
  - https://huggingface.co/spaces/Disty0/LCM_SoteMix_OpenVINO_CPU_Space
  - https://huggingface.co/Disty0/LCM_SoteMix

![image](https://github.com/rupeshs/fastsdcpu/assets/47277141/f235d8d7-8742-4a92-8377-f2d16a105778)

![image](https://github.com/rupeshs/fastsdcpu/assets/47277141/3589280f-6ea0-4ebe-8a9e-9fe82d33c1af)

**Comment by rupeshs** [comment]
@Disty0 Nice, I just added it in the branch https://github.com/rupeshs/fastsdcpu/tree/add-custom-models-support-for-openvino , negative prompt also working.
However, the old model `deinferno/LCM_Dreamshaper_v7-openvino` is not working. How did you convert SoteMix to openvino?

**Comment by Disty0** [comment]
Wrote this script for LCM conversion:
https://github.com/vladmandic/automatic/blob/master/cli/lcm-convert.py

Did OpenVINO conversion with optimum-cli.

**Comment by rupeshs** [comment]
@Disty0 thanks so it is LCM-LoRA,right? not directly distilled  model like `SimianLuo/LCM_Dreamshaper_v7`

**Comment by Disty0** [comment]
> @Disty0 thanks so it is LCM-LoRA,right? not directly distilled model like `SimianLuo/LCM_Dreamshaper_v7`

It's LCM LoRa baked in.

Also my model has both PyTorch and OpenVINO weights in the same repo.

**Comment by rupeshs** [comment]
@Disty0  cool so we can use any SD1.5 or sdxl models.

**Comment by rupeshs** [comment]
@Disty0 Just created simple tools for the conversion, thanks for your script https://github.com/rupeshs/lcm-openvino-converter

**Comment by rupeshs** [comment]
Released https://github.com/rupeshs/fastsdcpu/tree/v1.0.0-beta.13
