### ISSUE TITLE
OpenVino Mac?

### ISSUE THREAD

**Issue by cchance27** [rupeshs/fastsdcpu#65]
Just wondering why openvino on mac wasn't implemented did it not result in a similar speedup?

**Comment by rupeshs** [comment]
@cchance27 I don't have a Mac machine to test, if you can check it, please let me know.
https://github.com/rupeshs/fastsdcpu#fastsd-cpu-on-mac

**Comment by rupeshs** [comment]
@cchance27 Are you using M1?

**Comment by jamienk** [comment]
FYI on my 2015 Mac with 2.5 GHz Quad-Core Intel Core i7, this works and enables openvino

**Comment by rupeshs** [comment]
> FYI on my 2015 Mac with 2.5 GHz Quad-Core Intel Core i7, this works and enables openvino

Thanks for trying FastSD CPU
