### ISSUE TITLE
New version not starting up not working

### ISSUE THREAD

**Issue by AKDigitalAgency** [rupeshs/fastsdcpu#67]
I upgraded using "git pull" command, now when I try to run "Start.bat" or "Start-webui.bat" it opens up terminal window shows python version and than terminal window disappears :(
No desktop window or web terminal window shows up :(

PS running on win11 and previous version was working fine!

**Comment by gustrd** [comment]
Sometimes you need to update the pip libraries after doing a git pull.

Try to load the venv and run: pip install -U -r requirements.txt

**Comment by rupeshs** [comment]
@AKDigitalAgency you need to install packages using pip as @gustrd suggested.

**Comment by AKDigitalAgency** [comment]
I tried it  run this command > pip install -U -r requirements.txt
BUT 
That did not work, get same problem terminal window disappears and I don't know what the error was :(
IDK why this is happening it was working fine in previous version?!?!
Any other ideas how to fix it?

BTW Can you make terminal window not close automatically, instead keep it open until user close it manually?

**Comment by AKDigitalAgency** [comment]
OK problem solved finally figured out how to fix it :)
Steps:
1. Delete everything inside "ENV" folder
2. Run "Install.bat" again
3. Run "Start.bat"
4. Enjoy!

**Comment by gustrd** [comment]
Have you tried deleting the folder and installing again from the begging?
