### ISSUE TITLE
getting stuck while generating using GPU

### ISSUE THREAD

**Issue by noob-guy-dev** [rupeshs/fastsdcpu#72]
i'm using v1.0.0-beta.15

on CPU its working perfectly, and while generating using `set DEVICE = GPU` , i was able to generate image 2-3 times .

But now i'm unable to generate using GPU , its getting stuck.  

Command line output below:

Starting fastsdcpu...
Python command check :OK
Python version: 3.10.12
Running on Windows platform
OS: Windows-10-10.0.22621-SP0
Processor: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
Using device : GPU
Found 7 stable diffusion models in config/stable-diffusion-models.txt
Found 3 LCM-LoRA models in config/lcm-lora-models.txt
Found 4 OpenVINO LCM models in config/openvino-lcm-models.txt
Starting desktop GUI mode(Qt)
Torch datatype : torch.float32
Output path : D:\fastsdcpu\results
Reshape and compile
{'guidance_scale': 1.0,
 'image_height': 512,
 'image_width': 512,
 'inference_steps': 4,
 'lcm_lora': {'base_model_id': 'Lykon/dreamshaper-8',
              'lcm_lora_id': 'latent-consistency/lcm-lora-sdv1-5'},
 'lcm_model_id': 'rupeshs/LCM-dreamshaper-v7-openvino',
 'negative_prompt': 'worst quality,low quality,normal quality,lowres,watermark',
 'number_of_images': 1,
 'openvino_lcm_model_id': 'rupeshs/LCM-dreamshaper-v7-openvino',
 'prompt': 'best quality, masterpiece,1girl,white sweater',
 'seed': -1,
 'use_lcm_lora': False,
 'use_offline_model': True,
 'use_openvino': True,
 'use_safety_checker': False,
 'use_seed': False,
 'use_tiny_auto_encoder': False}
The config attributes {'algorithm_type': 'deis', 'lower_order_final': True, 'skip_prk_steps': True, 'solver_order': 2, 'solver_type': 'logrho', 'use_karras_sigmas': False} were passed to LCMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
D:\fastsdcpu\env\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Compiling the vae_decoder to GPU ...
Compiling the unet to GPU ...
Compiling the text_encoder to GPU ...
Compiling the vae_encoder to GPU ...
Model :rupeshs/LCM-dreamshaper-v7-openvino
Pipeline : OVStableDiffusionPipeline {
  "_class_name": "OVStableDiffusionPipeline",
  "_diffusers_version": "0.23.0",
  "_name_or_path": "rupeshs/LCM-dreamshaper-7",
  "feature_extractor": [
    "transformers",
    "CLIPFeatureExtractor"
  ],
  "requires_safety_checker": true,
  "safety_checker": [
    "stable_diffusion",
    "StableDiffusionSafetyChecker"
  ],
  "scheduler": [
    "diffusers",
    "LCMScheduler"
  ],
  "text_encoder": [
    "optimum",
    "OVModelTextEncoder"
  ],
  "text_encoder_2": [
    null,
    null
  ],
  "tokenizer": [
    "transformers",
    "CLIPTokenizer"
  ],
  "unet": [
    "optimum",
    "OVModelUnet"
  ],
  "vae_decoder": [
    "optimum",
    "OVModelVaeDecoder"
  ],
  "vae_encoder": [
    "optimum",
    "OVModelVaeEncoder"
  ]
}

The config attributes {'algorithm_type': 'deis', 'lower_order_final': True, 'skip_prk_steps': True, 'solver_order': 2, 'solver_type': 'logrho', 'use_karras_sigmas': False} were passed to LCMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
Using OpenVINO
Reshape and compile
Compiling the vae_decoder to GPU ...
Compiling the unet to GPU ...
Compiling the text_encoder to GPU ...
Compiling the vae_encoder to GPU ...
D:\fastsdcpu\env\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py:565: FutureWarning: `shared_memory` is deprecated and will be removed in 2024.0. Value of `shared_memory` is going to override `share_inputs` value. Please use only `share_inputs` explicitly.
  outputs = self.request(inputs, shared_memory=True)
  0%|                                                                                            | 0/4 [00:00<?, ?it/s]D:\fastsdcpu\env\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py:599: FutureWarning: `shared_memory` is deprecated and will be removed in 2024.0. Value of `shared_memory` is going to override `share_inputs` value. Please use only `share_inputs` explicitly.
  outputs = self.request(inputs, shared_memory=True)

**Comment by rupeshs** [comment]
Which GPU?

**Comment by noob-guy-dev** [comment]
integrated Iris gpu

I'm using intel i5-12500H

**Comment by Disty0** [comment]
GPU has compile time. Wait for around a minute.

**Comment by rupeshs** [comment]
@noob-guy-dev As @Disty0 mentioned GPU has some compile time for the first time subsequent runs will be faster,

**Comment by noob-guy-dev** [comment]
@rupeshs , it's been 30 minutes... still stuck

**Comment by rupeshs** [comment]
@noob-guy-dev please try cpu or do a fresh install.

**Comment by noob-guy-dev** [comment]
i did reinstall, but same issue , looks like no gpu for me , 

CPU works without any issue.

still thank you for your time @rupeshs @Disty0

**Comment by rupeshs** [comment]
@noob-guy-dev  Thanks for using FastSD CPU
