### ISSUE TITLE
Desktop app launch error

### ISSUE THREAD

**Issue by AKDigitalAgency** [rupeshs/fastsdcpu#75]
Did usual updates before launching "Start.bat" get error than terminal closes down BUT when launching "WebUI or RealTime" both are working fine!
Need to fix Desktop app GUI "config"???

![Screenshot 2023-11-26 094037](https://github.com/rupeshs/fastsdcpu/assets/147016521/6b73d7d2-4982-47b3-b58a-1065337bd1c3)

**Comment by rupeshs** [comment]
Please delete config/settings.yaml and run start.bat
