### ISSUE TITLE
torch==2.0.1 errors

### ISSUE THREAD

**Issue by onlyreportingissues** [rupeshs/fastsdcpu#78]
Terminal: 

chmod +x install.sh
./install.sh

Starting FastSD CPU env installation...
Found python command
Python version : 3.12.0
Looking in indexes: https://download.pytorch.org/whl/cpu

ERROR: Could not find a version that satisfies the requirement torch==2.0.1 (from versions: none)
ERROR: No matching distribution found for torch==2.0.1

**Comment by onlyreportingissues** [comment]
Terminal: 

chmod +x install.sh
./install.sh

Starting FastSD CPU env installation...
Found python command
Python version : 3.12.0
Looking in indexes: https://download.pytorch.org/whl/cpu

ERROR: Could not find a version that satisfies the requirement torch==2.0.1 (from versions: none)
ERROR: No matching distribution found for torch==2.0.1

**Comment by rupeshs** [comment]
Don't use Python 3.12 , you can use python 3.10 or python 3.11

**Comment by rupeshs** [comment]
@onlyreportingissues Pytorch yet not available for Python 3.12.
