### ISSUE TITLE
Crash: Changing Guidance scale maxes out RAM

### ISSUE THREAD

**Issue by onlyreportingissues** [rupeshs/fastsdcpu#79]
Setting Guidance to anything above 1.0 will max out (my 16GB of) RAM & crash the program.

**Comment by rupeshs** [comment]
Guidance scale 1.0 is the fastest, try to reduce number of images.How much RAM you have?

**Comment by rupeshs** [comment]
Can you share following details:
Mode : LCM or lcm-lora
Model : SD or sdxl

**Comment by onlyreportingissues** [comment]
I think it was rupeshs openvino dreamshaper.

**Comment by rupeshs** [comment]
Try LCM mode (It has low memory requirements.
