### ISSUE TITLE
Add the random seed number to the JSON file

### ISSUE THREAD

**Issue by DarioBerlanga** [rupeshs/fastsdcpu#80]
I LOVE your CPU SD implementation! Thank you so much!
I have a request, when we generate random seed images, we are hoping for something special.... and when it happens, we have a seed number of "-1".... please change this so that when the seed is set to random the real seed number will be saved in the JSON file.
Thank you so much!
:-)

**Comment by mykeehu** [comment]
I agree, because that way I can't lock the generated seed for minor tweaks if I don't know what the seed is.

**Comment by wbruna** [comment]
Sure. Unfortunately, it's not exactly trivial: the main repo diverged a bit from my earlier pull request  (#248 ), and those seeding changes build _on top_ of it, so I'll need some time to fix and test the merge conflicts.

**Comment by mykeehu** [comment]
@wbruna Thanks a lot for the PR, and I hope it will be included in the main build as soon as possible, because it would really improve the image generation and make it more consistent.
