### ISSUE TITLE
Tiny Auto Encoder - TAESD ruins the eyes

### ISSUE THREAD

**Issue by onlyreportingissues** [rupeshs/fastsdcpu#83]
I have used the settings shown here https://raw.githubusercontent.com/rupeshs/fastsdcpu/main/docs/images/fastsdcpu-gui.jpg with and without TAESD. TAESD dehumanizes the eyes & adds artefacts.

**Comment by rupeshs** [comment]
Yes it is expected, tased is fast but it can cause some artifacts.
