### ISSUE TITLE
how to add a negative prompt?

### ISSUE THREAD

**Issue by euneuber** [rupeshs/fastsdcpu#9]
Great project!

Some images have disturbing artifacts which can be omitted by applying a negative prompt. How to do this here?

**Comment by Amin456789** [comment]
batch count and more resolutions are welcome too.

[tested this online] anyway something i found out about this lcm dreamshaper model is = when u put it on lower sizes such as 384x384 352x352 etc alongside prompt such as = real, gopro, and giving a country it will give way more realistic images

example = a beautiful woman walking in tokyo in japan, gopro, real, close up

it gives realistic images more and less

it'll work i guess till we have negative prompt so we can put 3d render, painting, cartoon, anime, etc... in it. this is what i do with lyriel to get realistic images.

**Comment by rupeshs** [comment]
**WIP:** LCM-LoRA workflow supports negative prompt!
https://github.com/rupeshs/fastsdcpu/tree/add-sdxl-ssd-1b-support

**Comment by milen-prg** [comment]
> **WIP:** LCM-LoRA workflow supports negative prompt! https://github.com/rupeshs/fastsdcpu/tree/add-sdxl-ssd-1b-support
There are problems with disabled GUI controls on the Qt5 interface - the Neg Prompt field is disabled even the guidance scale set above 1 (Windows 10 Pro 64bit). The combo boxes with the model names also randomly are disabled.

**Comment by rupeshs** [comment]
Not randomly, as of now openvino does not support lcm-lora so when enable openvino those comobos will be disabled also negative prompt.Negative prompt only supported in Lcm-lora workflow

**Comment by milen-prg** [comment]
Apologize, I'm beginner and use sd on intuition. Thank, you!

**Comment by rupeshs** [comment]
@milen-prg  Thanks for using FastSD CPU

**Comment by rupeshs** [comment]
Added in the release https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.12
please checkout readme
