### ISSUE TITLE
Precompile unet to CPU

### ISSUE THREAD

**Issue by mak448a** [rupeshs/fastsdcpu#93]
Is there any way to compile unet to CPU beforehand and not have to recompile it every launch time?

**Comment by Micraow** [comment]
I think I have found a method.
The *compile* step is to turn the model into OpenVINO IR. By editing src/backend/openvino/pipelines.py can you cache the IR. 
Turn to lines like this:(in line 45,52,74)
```
ov_config={"CACHE_DIR": ""},
```

Input the cache directory to be used, and save the file.

Now run again, and the IR will be stored.The next time you launch, you don't have to wait!

**Need to mention that the cache can be quite big, so prepare a disk big enough. In addition, when you use another mode (previous txt2img, now img2img),or change the size of image, it still needs to compile and save the file for later use**

@rupeshs Maybe you can add this option to frontend😀

**Comment by mak448a** [comment]
@Micraow Want me to add a pull request?

**Comment by Micraow** [comment]
Wait, I find openvino still compile the unet and encoders again,even though I have set cache dir...
@rupeshs said that `It will compile at startup and when there is size change or model change etc`, so I doubt whether it is worth of caching.

**Comment by mak448a** [comment]
Ah ok! Thanks.

**Comment by rupeshs** [comment]
As of now, this is not feasible.

**Comment by Micraow** [comment]
Hi! I find [this](https://github.com/openvinotoolkit/stable-diffusion-webui/blob/5f4363300f531dc12f71bf42c0a6e817d2be6e7c/scripts/openvino_accelerate.py#L120) may be of some help. They can cache the compiled model! @rupeshs

**Comment by rupeshs** [comment]
I'm not sure about that, if any of the following parameters width, height, and number of images changed then we need to recompile the model https://github.com/rupeshs/fastsdcpu/blob/6b58a4d2cb187d3feeb4c6c80c828b2ede52ce16/src/frontend/utils.py#L7C1-L7C1.

**Comment by Micraow** [comment]
However, I think in most cases, we don't change those frequently.
