### ISSUE TITLE
fastsdcpu-1.0.0-beta.22 -install.bat fails

### ISSUE THREAD

**Issue by nguyenkm** [rupeshs/fastsdcpu#96]
In Windows 10 with Python 3:12.o installed I get the following error when executing instal.bat:

E:\Imaging_Video\fastsdcpu-1.0.0-beta.22>install.bat
Starting FastSD CPU env installation...
Python command check :OK
Python version: 3.12.0
Looking in indexes: https://download.pytorch.org/whl/cpu
ERROR: Could not find a version that satisfies the requirement torch==2.0.1 (from versions: none)
ERROR: No matching distribution found for torch==2.0.1
Collecting accelerate==0.23.0 (from -r E:\Imaging_Video\fastsdcpu-1.0.0-beta.22\requirements.txt (line 1))
  Obtaining dependency information for accelerate==0.23.0 from https://files.pythonhosted.org/packages/d9/92/2d3aecf9f4a192968035880be3e2fc8b48d541c7128f7c936f430d6f96da/accelerate-0.23.0-py3-none-any.whl.metadata
  Using cached accelerate-0.23.0-py3-none-any.whl.metadata (18 kB)
Collecting diffusers==0.23.0 (from -r E:\Imaging_Video\fastsdcpu-1.0.0-beta.22\requirements.txt (line 2))
  Obtaining dependency information for diffusers==0.23.0 from https://files.pythonhosted.org/packages/1f/05/0f0d539b542a983442c3824af7cca68c4979001befce3538d09d27d798bf/diffusers-0.23.0-py3-none-any.whl.metadata
  Using cached diffusers-0.23.0-py3-none-any.whl.metadata (17 kB)
Collecting transformers==4.35.0 (from -r E:\Imaging_Video\fastsdcpu-1.0.0-beta.22\requirements.txt (line 3))
  Obtaining dependency information for transformers==4.35.0 from https://files.pythonhosted.org/packages/9a/06/e4ec2a321e57c03b7e9345d709d554a52c33760e5015fdff0919d9459af0/transformers-4.35.0-py3-none-any.whl.metadata
  Using cached transformers-4.35.0-py3-none-any.whl.metadata (123 kB)
Collecting PyQt5 (from -r E:\Imaging_Video\fastsdcpu-1.0.0-beta.22\requirements.txt (line 4))
  Obtaining dependency information for PyQt5 from https://files.pythonhosted.org/packages/ca/ac/596e8ca16fd0634542d874c0d79219fc527ea7de73a5000092f60ecbf6e9/PyQt5-5.15.10-cp37-abi3-win_amd64.whl.metadata
  Using cached PyQt5-5.15.10-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
Collecting Pillow==9.4.0 (from -r E:\Imaging_Video\fastsdcpu-1.0.0-beta.22\requirements.txt (line 5))
  Using cached Pillow-9.4.0.tar.gz (50.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement openvino==2023.2.0 (from versions: none)
ERROR: No matching distribution found for openvino==2023.2.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
FastSD CPU env installation completed.
Press any key to continue . . .

**Comment by rupeshs** [comment]
@nguyenkm Please use Python 3.10 or 3.11...refer
https://github.com/rupeshs/fastsdcpu#fastsd-cpu-on-windows

**Comment by rupeshs** [comment]
Pytorch not supported on Python 3.12.

**Comment by nguyenkm** [comment]
I meant in the page where it says "(**Recommended:** Python 3.10 or 3.11)".  If it says **Required:** then it would have been obvious to me that my 3.12 would not have worked.  Others may make the same mistake as me and this would prevent that.😊
