### ISSUE TITLE
HIP / ROCm support planned?

### ISSUE THREAD

**Issue by onlyreportingissues** [rupeshs/fastsdcpu#98]
It works really well, tested it using SD.Next.
I also tried it with fastsdcpu, but it failed.

Maybe this can help: https://github.com/vladmandic/automatic/pull/2002/files#diff-b3ceed9306616c3f796c24f51d822762048d6032f4a4a0b290ac0e2d935eaaa1

**Comment by rupeshs** [comment]
@onlyreportingissues I don't have  AMD machine, so this is not planned
